# Project-wide Gradle settings.

# Memoria utilizada por Gradle
org.gradle.jvmargs=-Xmx1024m -Dfile.encoding=UTF-8

# AndroidX
android.useAndroidX=true

# Kotlin
kotlin.code.style=official

# Android
android.nonTransitiveRClass=true

# Compatibilidad con Kotlin integrado de AGP 9
android.disallowKotlinSourceSets=false