name: Android Tests

on:
  push:
    branches:
      - feat/Naurimar
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    name: Pruebas, Lint y APK
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Dar permisos a Gradle
        run: chmod +x gradlew

      - name: Ejecutar pruebas unitarias
        run: ./gradlew testDebugUnitTest

      - name: Ejecutar Android Lint
        run: ./gradlew lintDebug

      - name: Generar APK Debug
        run: ./gradlew assembleDebug

      - name: Guardar APK como Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PrestamoLabCTMA-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Ejecutar pruebas instrumentadas
        uses: reactivecircus/android-emulator-runner@v2
        with:
            api-level: 35
            target: google_apis
            arch: x86_64
            profile: pixel_2
            force-avd-creation: true
            emulator-options: -no-window -no-audio -no-boot-anim
            disable-animations: true
            script: ./gradlew connectedDebugAndroidTest